### PR TITLE
Fix education guide url

### LINKED ISSUE #188: Incorrect URLs in education mozilla guide
I tried to visit the websites provided here ( http://education.mozilla-community.org/modules/marketpulse_activities/step_2/) Missplaced url at 
[" >Printable Checklist

> Web App fields(and how to use them)
> Pricing & Plan Scenarios "]
> Also one URL missing in wiki mozilla.
> Here i attach a few images of incorrect URLs
> capture-20150517-060408
> capture-20150517-062406
> capture-20150517-065340

### PR DESCRIPTION
**Pull request by comzeradd**
- Fixes #188

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by emmairwin** [comment]
@comzeradd @johngian can we please merge this?

**Comment by johngian** [comment]
@emmairwin done :rocket:

**Comment by emmairwin** [comment]
yay  When will it go to production?

**Comment by comzeradd** [comment]
Deployed today

**Pull request merged**
