### PR TITLE
Top navigation menu

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@akatsoulas r?

**Comment by akatsoulas** [comment]
Is there a reason for replacing all the single quotes with double?

**Comment by comzeradd** [comment]
Well there is no strong arguments in favor of either choice (double vs single). I prefer double quotes mainly for two reasons. Double quotes are mandatory for json, so we don't have to change our mindset when parsing them on a js script and all the libs we already use (jquery, bootstrap, etc) are on the double quotes front ;)

**Comment by akatsoulas** [comment]
Well it's totally up to you. Personally, I prefer single for consistency with the rest of the codebase (except from the templates). 

Other than that, code looks good. r+(wc?)

**Pull request merged**
