### PR TITLE
Frontpage UI + Minor UI improvements

### PR DESCRIPTION
**Pull request by comzeradd**
It's not yet ready to be merged. We need a photo first and see how we can adjust the frontpage text accordingly.

### CODE REVIEW

**Comment by comzeradd** [comment]
PR updated. @ppapadeas can you have a look?

**Comment by ppapadeas** [comment]
https://partinfra.etherpad.mozilla.org/market-pulse-front

Changes described in the pad above. Also please test a smaller font.

**Comment by comzeradd** [comment]
PR updated

**Comment by comzeradd** [comment]
PR updated. @ppapadeas r?

**Comment by comzeradd** [comment]
shot

**Comment by ppapadeas** [comment]
R+ great work!

**Pull request merged**
