### PR TITLE
[Fixes #147] Unify all actions to detail view

### LINKED ISSUE #147: Unify ``edit/delete/clone`` UX
At the moment we show the following
- List view
  - Details, Clone
- Detailed view
  - Edit, Clone, Delete

I suggest to have this unified and either show only a `details` link in list view or show all the links in both views.

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

This is a small fix to unify all contribution actions under the detail view. No need to show clone on two different places.

**Comment by akatsoulas** [comment]
I would argue that it makes sense to have at least `clone` in the list all contributions view. Having the clone in the 'view all contributions' makes it much faster to clone a contribution than having to inspect each one separately. Moreover, since the clone will basically redirect to the edit page, we make sure that before cloning, our users will introspect each one of the fields.

**Comment by johngian** [comment]
As I have already said in #147 for me it makes sense to either show **all** the actions in the list view or **none**. I tend towards showing all the actions with discrete icons (eg small glyphicons).

**Comment by akatsoulas** [comment]
I am also in favor of showing all the icons. On the other hand it makes sense to force the users to review the contribution  before deleting/upvoting, whereas in clone is just easier and faster to be in the list view. Either way, I am OK with whatever the rest of the team decides. @ppapadeas thoughts?

**Comment by comzeradd** [comment]
I agree with @johngian. I don't like duplication. It should either show all actions or none. I'm leaning towards none. The list view omits many things around a specific contribution, so it makes sense to go on details to determine if that's really the one you want to edit/clone/delete.

**Comment by akatsoulas** [comment]
But this is not the case for cloning because you basically going to get a redirect to the edit view, so you are forced to inspect the contribution. Hiding cloning in the details, defeats its purpose, that of a fast contribution. Either way, r+ regrading the code.

**Pull request merged**
