### PR TITLE
Add BrowserID siteName/siteLogo args

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
I'm not should if we should leave siteLogo default to None and depend on `env`, or hardcode a default url.

@johngian r+

**Comment by johngian** [comment]
I suggest we implement this the way we are doing this in mozillians [1].

[1] https://github.com/mozilla/mozillians/blob/master/mozillians/settings/base.py#L312

**Comment by comzeradd** [comment]
I don't have a strong opinion on this, but I'd prefer we avoid complexity on settings file.

**Comment by johngian** [comment]
r+ :rocket:

**Pull request merged**
