### PR TITLE
Show contributor mozillian username instead of email

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by johngian** [comment]
@comzeradd tests are failing

**Comment by akatsoulas** [comment]
Is the username always exported from mozillians.org or is dependable on the privacy settings of each user? If each the latter, what happens in that case?

**Comment by johngian** [comment]
Username is exported in all API permission levels. Are we showing this to the public as well?

**Comment by comzeradd** [comment]
We want to display username instead of emails on the contributions list. I could nest this inside a try clause, just to be safe. But we need to show something in case `mozillians_username` is missing.

**Comment by johngian** [comment]
Travis is failing because of the API queries. I suggest we do the migration using a management command.

**Comment by comzeradd** [comment]
@johngian PR updated

**Comment by johngian** [comment]
Let's move this under `auth` app.

**Comment by comzeradd** [comment]
PR updated

**Comment by johngian** [comment]
r+

**Pull request merged**
