### PR TITLE
Custom 404/500 error pages

### LINKED ISSUE #163: Add a custom 404 error template.

### LINKED ISSUE #164: Add a custom 500 error template.

### PR DESCRIPTION
**Pull request by comzeradd**
- Fixes #163 
- Fixes #164

### CODE REVIEW

**Comment by comzeradd** [comment]
@akatsoulas r?

**Comment by johngian** [comment]
Please add the new `404` and `500` handlers to `settings.DEBUG` urls as well.

https://github.com/mozilla/mozillians/blob/master/mozillians/urls.py#L59

**Comment by comzeradd** [comment]
@johngian PR updated

**Comment by akatsoulas** [comment]
Also, since these errors are specific to marketpulse, I would move them to the main app.

**Comment by johngian** [comment]
@akatsoulas We can keep them in `base` since these errors are generic `404` and `500`.

**Comment by johngian** [comment]
Tested it locally and error pages look fine.
r+ from me

@akatsoulas r?

**Comment by akatsoulas** [comment]
The comment was non-blocking so merge away :)

**Pull request merged**
